extends RefCounted
class_name RuleConfigs

const RULE_FREEZE_VERSION := "v1"

const GLOBAL := {
	"RULE_FREEZE_VERSION": RULE_FREEZE_VERSION,
	"NAVAL_TEMPLATE_ENABLED": false,
	"GRASS_SAND_SPLIT_ENABLED": false
}

const TERRAIN := {
	"ARCHER_VS_FOREST_BLOCK_MODE": "HARD_BLOCK",
	"ARCHER_TARGET_BLOCKED_BY_FOREST": "ARCHER_TARGET_BLOCKED_BY_FOREST"
}

const COMBAT := {
	"ARCHER_SPECIAL_COEFF_APPLY_STAGE": "FINAL_DAMAGE",
	"ARCHER_SPECIAL_COEFF": 1.20,
	"CATAPULT_VS_UNIT_COEFF": 0.70
}

const LOGISTICS := {
	"RESOURCE_ZERO_PENALTY_ENABLED": true,
	"RESOURCE_ZERO_PENALTY_ORDER": ["FOOD", "MONEY", "WEAPON", "TROOP_SOURCE"]
}

const CITY := {
	"WOUNDED_RECOVERY_AFFECTED_BY_CITY_STATE": true,
	"WOUNDED_RECOVERY_STATE_FACTOR_PEACE": 1.00,
	"WOUNDED_RECOVERY_STATE_FACTOR_INVASION": 0.80,
	"WOUNDED_RECOVERY_STATE_FACTOR_SIEGE": 0.50
}

const TACTIC := {
	"TACTIC_POINT_COST_BASIC_DAMAGE": 25,
	"TACTIC_POINT_COST_CONTROL": 35,
	"TACTIC_POINT_COST_BUFF_DEBUFF": 20,
	"TACTIC_POINT_COST_MOBILITY": 30,
	"TACTIC_CAST_FAIL_BY_WEATHER": false
}

const LOYALTY := {
	"LOYALTY_MAX": 255,
	"LOYALTY_NO_REBELLION_THRESHOLD": 100,
	"LOYALTY_REWARD_BASE_GAIN": 12
}
