extends RefCounted
class_name ReasonCodes

const OK := "OK"

const CITY_OWNER_MISMATCH := "CITY_OWNER_MISMATCH"
const INVALID_TROOP_SOURCE := "INVALID_TROOP_SOURCE"
const CITY_TROOP_SOURCE_NOT_ENOUGH := "CITY_TROOP_SOURCE_NOT_ENOUGH"
const CITY_WEAPON_NOT_ENOUGH := "CITY_WEAPON_NOT_ENOUGH"

const SUPPLY_OUT_OF_RANGE := "SUPPLY_OUT_OF_RANGE"
const NOT_TRANSPORT_UNIT := "NOT_TRANSPORT_UNIT"
const TRANSPORT_ALREADY_EXECUTED := "TRANSPORT_ALREADY_EXECUTED"
const SUPPLY_ACTION_LIMIT_REACHED := "SUPPLY_ACTION_LIMIT_REACHED"
const NOTHING_TO_SUPPLY := "NOTHING_TO_SUPPLY"

const ATTACKER_ALREADY_EXECUTED := "ATTACKER_ALREADY_EXECUTED"
const SAME_FACTION_CITY := "SAME_FACTION_CITY"
const TARGET_NOT_ADJACENT := "TARGET_NOT_ADJACENT"
const CITY_ENTRY_PRECHECK_FAILED := "CITY_ENTRY_PRECHECK_FAILED"
